#!/usr/bin/ruby
source 'https://rubygems.org'
gem 'typhoeus'
gem 'json'

gem 'irb'
gem 'pry'
gem 'pry-byebug' if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.2.0')
gem 'pry-coolline'
gem 'pry-doc'
gem 'pry-git'
gem 'pry-inline'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'pry-state'
gem 'pry-syntax-hacks'
gem 'pry-theme'
gem 'digest-crc'

gem "http"
gem "http-2"


gem 'minitest'
gem 'minitest-reporters'

